---
namespace: linkerd-easyauth

nodeSelector: &default_node_selector
  kubernetes.io/os: linux

tolerations: &default_tolerations

webhook:
  image:
    name: aatarasoff/linkerd-easyauth-webhook
    version: 0.1.0
    pullPolicy: IfNotPresent

  logLevel: info

  failurePolicy: Fail

  namespaceSelector:
  objectSelector:

  nodeSelector: *default_node_selector
  tolerations: *default_tolerations

policies:
  # linkerd sys namespaces should has access to proxy admin port
  linkerd:
    namespaces:
      - linkerd
      - linkerd-viz

  # all namespaces with meshed apps (because policies are namespaced scope)
  meshedApps:
    namespaces: []

  # policy for ingress
  ingress:
    enabled: false
    namespace: ingress

  # policy for monitoring (eg. external prometheus)
  monitoring:
    enabled: false
    namespace: monitoring
