{{- range .Values.policies.meshedApps.namespaces }}
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: {{ . }}
  name: linkerd-admin-port
spec:
  podSelector:
    matchLabels:
      linkerd.io/easyauth: "true"
  port: linkerd-admin
---
apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  namespace: {{ . }}
  name: linkerd-authn
spec:
  identities:
  {{- range $.Values.policies.linkerd.namespaces }}
    - "*.{{ . }}.serviceaccount.identity.linkerd.cluster.local"
  {{- end }}
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  namespace: {{ . }}
  name: linkerd-admin-allow
spec:
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: linkerd-admin-port
  requiredAuthenticationRefs:
    - name: linkerd-authn
      kind: MeshTLSAuthentication
      group: policy.linkerd.io
{{- if $.Values.policies.monitoring.enabled }}
---
apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  namespace: {{ . }}
  name: monitoring-authn
spec:
  identities:
    - "*.{{ $.Values.policies.monitoring.namespace }}.serviceaccount.identity.linkerd.cluster.local"
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  namespace: {{ . }}
  name: linkerd-monitoring-allow
spec:
  targetRef:
    group: core
    kind: Namespace
    name: {{ . }}
  requiredAuthenticationRefs:
    - name: monitoring-authn
      kind: MeshTLSAuthentication
      group: policy.linkerd.io
{{ end }}
{{- if $.Values.policies.ingress.enabled }}
---
apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  namespace: {{ . }}
  name: ingress-authn
spec:
  identities:
    - "*.{{ $.Values.policies.ingress.namespace }}.serviceaccount.identity.linkerd.cluster.local"
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  namespace: {{ . }}
  name: linkerd-ingress-allow
spec:
  targetRef:
    group: core
    kind: Namespace
    name: {{ . }}
  requiredAuthenticationRefs:
    - name: ingress-authn
      kind: MeshTLSAuthentication
      group: policy.linkerd.io
{{ end }}
---
apiVersion: policy.linkerd.io/v1alpha1
kind: NetworkAuthentication
metadata:
  name: cluster-network-authn
  namespace: {{ . }}
spec:
  networks:
    {{- range $.Values.policies.clusterNetwork.cidr }}
    - cidr: {{ . }}
    {{- end }}
    {{- if $.Values.policies.clusterNetwork.generator }}
    {{- range $i, $e1 := untilStep (int $.Values.policies.clusterNetwork.generator.low1) (int $.Values.policies.clusterNetwork.generator.high1) 1 }}
    {{- range $j, $e2 := untilStep (int $.Values.policies.clusterNetwork.generator.low2) (int $.Values.policies.clusterNetwork.generator.high2) 1 }}
    - cidr: {{ $.Values.policies.clusterNetwork.generator.octet0 }}.{{ $e1 }}.{{ $e2 }}.{{ $.Values.policies.clusterNetwork.generator.octet3 }}/32
    {{- end }}
    {{- end }}
    {{- end }}
{{ end }}
