{{- range .Values.policies.meshedApps.namespaces }}
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: {{ . }}
  name: linkerd-admin-port
  labels:
    linkerd.io/server-type: common
spec:
  podSelector:
    matchLabels:
      linkerd.io/easyauth: true
  port: linkerd-admin
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: {{ . }}
  name: app-serving-port
  labels:
    linkerd.io/server-type: common
spec:
  podSelector:
    matchLabels:
      linkerd.io/easyauth: true
  port: linkerd-admin
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  namespace: {{ . }}
  name: linkerd-admin-allow
spec:
  server:
    name: linkerd-admin-port
  client:
    meshTLS:
      identities:
      {{- range $.Values.policies.linkerd.namespaces }}
        - "*.{{ . }}.serviceaccount.identity.linkerd.cluster.local"
      {{- end }}
---
{{- if $.Values.policies.monitoring.enabled }}
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  namespace: {{ . }}
  name: linkerd-monitoring-allow
spec:
  server:
    selector:
      matchLabels:
        linkerd.io/server-type: common
  client:
    meshTLS:
      identities:
        - "*.{{ $.Values.policies.monitoring.namespace }}.serviceaccount.identity.linkerd.cluster.local"
{{ end }}
{{- if $.Values.policies.ingress.enabled }}
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  namespace: {{ . }}
  name: linkerd-ingress-allow
spec:
  server:
    selector:
      matchLabels:
        linkerd.io/server-type: common
  client:
    meshTLS:
      identities:
        - "*.{{ $.Values.policies.ingress.namespace }}.serviceaccount.identity.linkerd.cluster.local"
{{ end }}
{{ end }}